services:
  postgres:
    image: postgres:17
    container_name: ai_resume_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: resume_user
      POSTGRES_PASSWORD: resume_password
      POSTGRES_DB: resume_analyzer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: